# Generated by Django 4.2.7 on 2025-06-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='MeterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan', models.CharField(help_text='Meter Point Administration Number', max_length=13, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['mpan'],
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Physical meter serial number', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='meter_readings.meterpoint')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('register_type', models.CharField(choices=[('E', 'Economy 7 Day'), ('N', 'Economy 7 Night'), ('S', 'Standard')], default='S', max_length=1)),
                ('register_id', models.CharField(default='00000', help_text='Register identifier', max_length=5)),
                ('value', models.DecimalField(decimal_places=2, help_text='Cumulative electricity consumption', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meter_readings.flowfile')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meter_readings.meter')),
            ],
            options={
                'ordering': ['-reading_date', 'meter'],
                'unique_together': {('meter', 'reading_date', 'register_type', 'register_id')},
            },
        ),
    ]
